// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

/**
 * Item in *About → Skills*
 */
export interface AboutDocumentDataSkillsItem {
  /**
   * Skill Title field in *About → Skills*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g., Content Strategy
   * - **API ID Path**: about.skills[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *About → Skills*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Brief description of this skill
   * - **API ID Path**: about.skills[].description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;
}

/**
 * Item in *About → Experience*
 */
export interface AboutDocumentDataExperienceItem {
  /**
   * Job Title field in *About → Experience*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g., Senior Marketing Manager
   * - **API ID Path**: about.experience[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Company field in *About → Experience*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g., Acme Inc.
   * - **API ID Path**: about.experience[].company
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  company: prismic.KeyTextField;

  /**
   * Dates field in *About → Experience*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g., Jan 2020 - Present
   * - **API ID Path**: about.experience[].dates
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  dates: prismic.KeyTextField;

  /**
   * Description field in *About → Experience*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Describe your role and achievements...
   * - **API ID Path**: about.experience[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Item in *About → Social Links*
 */
export interface AboutDocumentDataSocialLinksItem {
  /**
   * Platform field in *About → Social Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g., LinkedIn, Twitter, GitHub
   * - **API ID Path**: about.socialLinks[].platform
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  platform: prismic.KeyTextField;

  /**
   * URL field in *About → Social Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: https://...
   * - **API ID Path**: about.socialLinks[].url
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  url: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Content for About documents
 */
interface AboutDocumentData {
  /**
   * Name field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g., Dustin Litorja
   * - **API ID Path**: about.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Role/Title field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g., Content Strategist & Marketing Consultant
   * - **API ID Path**: about.role
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  role: prismic.KeyTextField;

  /**
   * Bio field in *About*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Write a brief bio about yourself...
   * - **API ID Path**: about.bio
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  bio: prismic.RichTextField;

  /**
   * Profile Image field in *About*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.profileImage
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  profileImage: prismic.ImageField<"square">;

  /**
   * Resume Link field in *About*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link to your resume PDF or document
   * - **API ID Path**: about.resumeLink
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  resumeLink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  > /**
   * Skills field in *About*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: about.skills[]
   * - **Tab**: Skills
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */;
  skills: prismic.GroupField<Simplify<AboutDocumentDataSkillsItem>> /**
   * Experience field in *About*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: about.experience[]
   * - **Tab**: Experience
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */;
  experience: prismic.GroupField<Simplify<AboutDocumentDataExperienceItem>> /**
   * Social Links field in *About*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: about.socialLinks[]
   * - **Tab**: Social Links
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */;
  socialLinks: prismic.GroupField<Simplify<AboutDocumentDataSocialLinksItem>>;
}

/**
 * About document from Prismic
 *
 * - **API ID**: `about`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<AboutDocumentData>, "about", Lang>;

/**
 * Content for Site Settings documents
 */
interface SiteSettingsDocumentData {
  /**
   * Site Title field in *Site Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g., Dustin Litorja
   * - **API ID Path**: site_settings.site_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  site_title: prismic.KeyTextField;

  /**
   * Hero Headline field in *Site Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g., Dustin Litorja
   * - **API ID Path**: site_settings.hero_headline
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  hero_headline: prismic.KeyTextField;

  /**
   * Hero Subtitle field in *Site Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g., Content Strategy | Marketing | Ops | Videography | Photography
   * - **API ID Path**: site_settings.hero_subtitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  hero_subtitle: prismic.KeyTextField;

  /**
   * Hero Description field in *Site Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g., Welcome to Dustin Litorja's Portfolio
   * - **API ID Path**: site_settings.hero_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  hero_description: prismic.KeyTextField;

  /**
   * Announcement Badge (Optional) field in *Site Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g., Available for freelance work
   * - **API ID Path**: site_settings.announcement_badge
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  announcement_badge: prismic.KeyTextField;

  /**
   * Show Announcement Badge field in *Site Settings*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: site_settings.show_announcement
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  show_announcement: prismic.BooleanField /**
   * Meta Title field in *Site Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Page title for SEO
   * - **API ID Path**: site_settings.meta_title
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Site Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Description for SEO and social sharing
   * - **API ID Path**: site_settings.meta_description
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Keywords field in *Site Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Comma-separated keywords
   * - **API ID Path**: site_settings.meta_keywords
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_keywords: prismic.KeyTextField;

  /**
   * Open Graph Image field in *Site Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: site_settings.og_image
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  og_image: prismic.ImageField<never> /**
   * GitHub URL field in *Site Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: https://github.com/username
   * - **API ID Path**: site_settings.github_url
   * - **Tab**: Social Links
   * - **Documentation**: https://prismic.io/docs/fields/link
   */;
  github_url: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * LinkedIn URL field in *Site Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: https://linkedin.com/in/username
   * - **API ID Path**: site_settings.linkedin_url
   * - **Tab**: Social Links
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  linkedin_url: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Twitter/X URL field in *Site Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: https://twitter.com/username
   * - **API ID Path**: site_settings.twitter_url
   * - **Tab**: Social Links
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  twitter_url: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Instagram URL field in *Site Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: https://instagram.com/username
   * - **API ID Path**: site_settings.instagram_url
   * - **Tab**: Social Links
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  instagram_url: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  > /**
   * Footer Text field in *Site Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g., © 2025 Dustin Litorja. All rights reserved.
   * - **API ID Path**: site_settings.footer_text
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  footer_text: prismic.KeyTextField;

  /**
   * Footer Tagline field in *Site Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g., Creative developer and designer...
   * - **API ID Path**: site_settings.footer_tagline
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  footer_tagline: prismic.KeyTextField;
}

/**
 * Site Settings document from Prismic
 *
 * - **API ID**: `site_settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SiteSettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SiteSettingsDocumentData>,
    "site_settings",
    Lang
  >;

export type AllDocumentTypes = AboutDocument | SiteSettingsDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AboutDocument,
      AboutDocumentData,
      AboutDocumentDataSkillsItem,
      AboutDocumentDataExperienceItem,
      AboutDocumentDataSocialLinksItem,
      SiteSettingsDocument,
      SiteSettingsDocumentData,
      AllDocumentTypes,
    };
  }
}
